#!/usr/bin/env bash
# Validates Conventional Commits over a range.
#
#   scripts/check-commits.sh <base> <head>
#   scripts/check-commits.sh                 # defaults to origin/main..HEAD
#
# Deliberately a shell script rather than commitlint: this repository has no
# Node toolchain, and adding one to lint commit messages would be the only
# reason it existed.
set -uo pipefail

BASE="${1:-origin/main}"
HEAD_REF="${2:-HEAD}"

TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
# type(optional-scope)!: subject
PATTERN="^(${TYPES})(\([a-z0-9._/-]+\))?!?: .+"
MAX_SUBJECT=80

fail=0
while IFS= read -r sha; do
    [ -z "$sha" ] && continue
    subject="$(git log -1 --format=%s "$sha")"

    # Merge commits are generated by GitHub and are not authored messages.
    if [ "$(git rev-list --parents -n 1 "$sha" | wc -w)" -gt 2 ]; then
        continue
    fi

    if ! printf '%s' "$subject" | grep -Eq "$PATTERN"; then
        echo "✗ ${sha:0:8} does not match <type>(<scope>): <subject>"
        echo "    $subject"
        fail=1
        continue
    fi
    if [ "${#subject}" -gt "$MAX_SUBJECT" ]; then
        echo "✗ ${sha:0:8} subject is ${#subject} characters, limit is $MAX_SUBJECT"
        echo "    $subject"
        fail=1
        continue
    fi
    echo "✓ ${sha:0:8} $subject"
done < <(git rev-list "$BASE..$HEAD_REF")

if [ "$fail" -ne 0 ]; then
    cat <<'EOF'

Commit subjects must read: <type>(<scope>): <subject>
  types: feat fix docs style refactor perf test build ci chore revert
  scopes used here: core, app, daemon, models, keychain, server, ui

See CONTRIBUTING.md.
EOF
    exit 1
fi
echo "All commit messages look right."
